name: evolution-standalone

services:
  evolution:
    image: evoapicloud/evolution-api:v2.3.7
    container_name: evolution-api
    restart: unless-stopped
    volumes:
      - ./evolution-data:/evolution/instances
    environment:
      SERVER_URL: http://localhost:8080
      DATABASE_ENABLED: "true"
      DATABASE_PROVIDER: postgresql
      DATABASE_URL: postgresql://postgres:${POSTGRES_PASSWORD:-postgres}@localhost:5432/evolution?sslmode=disable
      AUTHENTICATION_API_KEY: ${EVOLUTION_API_KEY:-minha-chave-aqui}
      AUTHENTICATION_EXPOSE_KEY_FILES: "true"
      AUTHENTICATION_TYPE: apikey
      AUTHENTICATION_DISABLE_FRONTEND: "false"
      LOG_LEVEL: info
      WEBHOOK_ENABLED: "false"
      DEL_INSTANCE: "false"
    ports:
      - "8080:8080"